services:
  redis:
    hostname: 'redis'
    command: 'redis-server --appendonly yes --requirepass redispassword'
    volumes:
      - redis_data:/data
    networks:
      - web-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:

networks:
  web-public:
    external: true
